### PR TITLE
Adds Support For PwnedPasswords API

### PR DESCRIPTION
**Pull request by Grantimus9**
These add support for checking if a password is pwned.

### CODE REVIEW

**Review by techgaun — APPROVED** [review]

**Comment by techgaun** [comment]
cool, thanks @Grantimus9 for your contribution :+1:

**Comment by Grantimus9** [comment]
Cool, what's it take to get the hex package updated? This is just a minor version bump. I plan to start using this in a project.

**Comment by techgaun** [comment]
@Grantimus9 I will make a new release tonight and let you know

**Comment by techgaun** [comment]
@Grantimus9 it has been released to hex. Thanks again for your contribution. Much appreciated

**Pull request merged**
